require('./User.js');
require('./Coach.js');
require('./Athlete.js');
require('./Team.js');
require('./Exercise.js');
require('./Assignment.js');
require('./ExerciseLog.js');
require('./MealLog.js');
require('./GameEvent.js');